version: "3"
services:
  main:
    container_name: go-base-service
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 8088:8088
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3320}
      - DB_USER=${DB_USER:-root}
      - DB_NAME=${DB_NAME:-db-demo}
      - DB_PASS=${DB_PASS:-root}
    networks:
      - mynet
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db-demo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3320:3306
    volumes:
      - mysql:/var/lib/user
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 3
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
  db-test:
    container_name: db-test
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db-demo-test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3322:3306
    volumes:
      - go-base-test:/var/lib/user
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    restart: "no"
    cap_add:
      - all
    environment:
      MYSQL_DATABASE: db-master
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3344:3306
    volumes:
      - ./conf/db_master/data:/var/lib/mysql
      - ./conf/db_master/my.cnf:/etc/my.cnf
    networks:
      - overlay
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]

  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    restart: "no"
    cap_add:
      - all
    environment:
      MYSQL_DATABASE: db-slave
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3355:3306
    volumes:
      - ./conf/db_slave/data:/var/lib/mysql
      - ./conf/db_slave/my.cnf:/etc/my.cnf
    networks:
      - overlay
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
volumes:
  mysql:
  go-base-test:
networks:
  mynet:
    driver: bridge
  overlay: