name: Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: "app's name"
        required: true
        type: string
jobs:
  say-hello:
    runs-on: codebuild-quang-test-${{ github.run_id }}-${{ github.run_attempt }}
    container: mcr.microsoft.com/playwright:v1.52.0-jammy
    
    steps:
      - name: Print greeting
        run: echo "🚀 Hello, World ${{ inputs.base_url_app }} from GitHub Actions!"
