name: Hello World

on:
  push:
    tags:
      - 'test*'
jobs:
  say-hello:
    runs-on: codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Print greeting
        run: echo "🚀 Hello, World from GitHub Actions!"
      - name: call API
        run: curl http://10.0.20.171:3000